language: cpp
os: osx
osx_image: xcode8.3
env: CXX=g++ PYTHON=python CXXFLAGS=-std=c++11

sudo: required
before_install:
  - brew tap inilabs/inilabs
  - brew update
  - /usr/bin/yes | pip uninstall numpy;
# Compiler selection
compiler:
  - g++

install:
#  - brew install cmake pkg-config libusb
  # - brew install / upgrade boost
  - set -e
#  - brew install opencv
  - brew install libcaer
#   - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
#   - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}

# Build steps
script:
  - cd examples
  - mkdir build
  - cd build
  - cmake ..
  - make

# -- The C compiler identification is AppleClang 8.1.0.8020042
# -- The CXX compiler identification is AppleClang 8.1.0.8020042
# -- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
# -- Detecting C compiler ABI info - done
# -- Detecting C compile features - done
# -- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
# -- Detecting CXX compiler ABI info - done
# -- Detecting CXX compile features - done
# -- Boost version: 1.67.0
# -- Found OpenCV: /usr/local/Cellar/opencv/3.4.1_5 (found version "3.4.1")
# -- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2")
# -- Checking for module 'libcaer'
# --   Found libcaer, version 2.4.2
# found libcaer
# found EVL
# include directory of EVL is
# /Users/shintaro/work/evl/src
# source of EVL is
# /Users/shintaro/work/evl/src/evl/core/davisio.hpp/Users/shintaro/work/evl/src/evl/core/shutdown.hpp/Users/shintaro/work/evl/src/evl/core/types.hpp/Users/shintaro/work/evl/src/evl/core/davisio.cpp/Users/shintaro/work/evl/src/evl/core/shutdown.cpp/Users/shintaro/work/evl/src/evl/imgproc/detection.hpp/Users/shintaro/work/evl/src/evl/imgproc/detection.cpp
# -- Boost version: 1.67.0
# found libcaer
# -- Found OpenGL: /System/Library/Frameworks/OpenGL.framework
# -- Found GLUT: /System/Library/Frameworks/GLUT.framework
# -- Boost version: 1.67.0
# found libcaer
# -- Configuring done
# -- Generating done
# -- Build files have been written to: /Users/shintaro/work/evl/examples/build
