version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout
      - run: apt-get update
      - run:
          name: Install dependencies
          command: apt-get install -y git cmake libusb-dev && bash install_dependencies.sh && apt-get install -y libboost-all-dev
      - run:
          name: Build
          command: cd examples; mkdir build; cd build; cmake ..; make
