version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout
      - run: apt-get update && apt-get upgrade
      - run:
          name: Install dependencies
          command: apt-get install -y git cmake libusb-dev libusb-1.0-0-dev libboost-all-dev && apt-get update && bash install_dependencies.sh
      - run:
          name: Build
          command: cd examples; mkdir build; cd build; cmake ..; make
