version: 2
jobs:
  build:
    docker:
      - image: ubuntu

    steps:
      - checkout
      - run:
          name: Initial settings
          command: apt-get update && apt-get install -y sudo && export DEBIAN_FRONTEND=noninteractive && sudo -E apt-get update &&  sudo -E apt-get install -y -qq tzdata
      - run:
          name: Install prerequists
          command: sudo -E apt-get install -y -qq git cmake libusb-dev libusb-1.0-0-dev
      - run:
          name: Install Boost
          command: sudo -E apt-get install -y -qq libboost-all-dev
      - run:
          name: Install libeigen3
          command: sudo -E apt-get install libeigen3-dev
      - run:
          name: Install OpenCV
          command: sudo -E apt-get install -y -qq libopencv-dev
      - run:
          name: Install OpenGL
          command: sudo -E apt-get install -y -qq libglu1-mesa-dev freeglut3-dev mesa-common-dev
      - run:
          name: Install dependencies
          command: sudo -E apt-get update && bash install_dependencies.sh
      - run:
          name: Build
          command: cd examples; mkdir build; cd build; cmake ..; make
